create database customer_data;
use customer_data;
CREATE TABLE customers(
    `customer_id` INT auto_increment primary key,
    `age` INT,
    `gender` VARCHAR(20),
    `item_purchased` VARCHAR(100),
    `category` VARCHAR(50),
    `purchase_amount` DECIMAL(10,2),
    `location` VARCHAR(50),
    `size` VARCHAR(20),
    `color` VARCHAR(30),
    `season` VARCHAR(20),
    `review_rating` DECIMAL(3,2),
    `subscription_status` VARCHAR(20),
    `shipping_type` VARCHAR(30),
    `discount_applied` VARCHAR(10),
    `previous_purchases` INT,
    `payment_method` VARCHAR(30),
    `frequency_of_purchases` VARCHAR(30)
);
select * from customers limit 20;
-- Q.1 What is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as revenue from customers group by gender;
-- Q.2 Which customers used discount but still spent more than the average purchase amount?
select customer_id, purchase_amount from customers where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customers);
-- Q.3 Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating),2)  as "Average Product Rating" from customers group by item_purchased order by avg(review_rating) desc limit 5;
-- Q.4 Compare the average purchase amounts between standard and express shipping?
select shipping_type, round(avg(purchase_amount),2) from customers where shipping_type in ('Standard','Express') group by shipping_type;
-- Q.5 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers?
select subscription_status, count(customer_id) as total_customers,  round(avg(purchase_amount),2) as avg_spend, 
round(sum(purchase_amount),2) as total_revenue from customers group by subscription_status order by total_revenue,avg_spend desc;
-- Q.6 Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, round(sum(case when discount_applied = 'Yes' Then 1 Else 0 end) /
count(*) *100,2) as discount_rate from customers group by item_purchased order by discount_rate desc limit 5;
-- Q.7 Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customers)
select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;
-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customers
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 -- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status;
-- Q10. What is the revenue contribution of each age group? 
SELECT 
    age,
    SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY age
ORDER BY total_revenue desc;
